version: "3"

services:
  jhub:
    image: jupyterhub:latest
    container_name: jupyterhub
    ports:
      - 8000:8000
    networks:
      - jupyterhub
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  jupyterhub:
    name: jupyterhub
